### ISSUE TITLE
Cannot find psycopg2-binary

### ISSUE THREAD

**Issue by frafra** [frostming/pdm-packer#11]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./nina_database_manager.pyz/__main__.py", line 2, in <module>
  File "/usr/local/lib/python3.8/site-packages/manager.py", line 9, in <module>
    import psycopg2
  File "<frozen zipimport>", line 259, in load_module
  File "./nina_database_manager.pyz/psycopg2/__init__.py", line 51, in <module>
ModuleNotFoundError: No module named 'psycopg2._psycopg'
```

**Describe the bug**
`psycopg2-binary` is a dependency of the project, but it is not found when I try to execute the `.pyz` zip file.

**To Reproduce**
1. Add `psycopg2-binary`
2. Import `psycopg2` in your app
3. Pack your app
4. Run it
5. See error

**Expected behavior**
`psycopg2` should be imported as usual.

**System (please complete the following information):**
- `pdm-packer` version: 0.2.1
- Python version: 3.8
- OS: Linux

**Additional context**
Other dependencies, such as `ldap`, seems to work as usual.

**Comment by frostming** [comment]
This is an OS limitation: https://docs.python.org/3/library/zipapp.html#caveats

pdm-packer can't help with this case.
