### ISSUE TITLE
How do you pack all files within project and access them?

### ISSUE THREAD

**Issue by mgzenitech** [frostming/pdm-packer#18]
Probably just some examples I'm missing but how do you pack and access resource files? For example my project consists of:
```
lib/python/.... (python modules)
run.py (run function as entrypoint)
.env
README.md
etc.
```

How do I access .env file for example? because now my app is failing due to `dotenv.load_dotenv` function

```
Traceback (most recent call last):
  File "/home/mariusg/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mariusg/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mariusg/Documents/Projects/infra-terraform/./app.pyz/__main__.py", line 3, in <module>
  File "/tmp/pdm-pack-rpnrz65t/lib/run.py", line 10, in run
    load_dotenv()
  File "/tmp/pdm-pack-rpnrz65t/lib/dotenv/main.py", line 331, in load_dotenv
  File "/tmp/pdm-pack-rpnrz65t/lib/dotenv/main.py", line 298, in find_dotenv
  File "/tmp/pdm-pack-rpnrz65t/lib/dotenv/main.py", line 255, in _walk_to_root
OSError: Starting path not found
```

run.py:
```python
#!/usr/bin/env python3

from dotenv import load_dotenv

def run():
    # Load up .env files
    load_dotenv()
```

Package command:
```
pdm pack -m run:run -c --pyc --no-py --exe -o app.pyz
```

**Comment by frostming** [comment]
resource files must be either read from outside of the zip, like a normal file, or loaded using [`importlib.resources`](https://docs.python.org/3.12/library/importlib.resources.html) utilities, in this way the resource must belong to a package.
